### PR TITLE
Import MonadFail explicitly so it builds on GHC 8.6.5

### PR DESCRIPTION
**Pull request by endgame**
Looks like MonadFail needs to be imported explicitly on old GHC, as it doesn't get into Prelude until 8.8.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
I'm a bit confused. The CI shows that `blank-canvas` [builds without issue](https://travis-ci.org/ku-fpg/blank-canvas/jobs/642967259) on GHC 8.6.5. If it is not building for you, can you post the complete build log showing the failure? I worry that the fix here is just applying a bandage over a deeper issue.

**Comment by endgame** [comment]
```
$ cabal new-build
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - blank-canvas-0.8 (lib) (file Graphics/Blank/Style.hs changed)
Preprocessing library for blank-canvas-0.8..
Building library for blank-canvas-0.8..
[18 of 18] Compiling Graphics.Blank.Style ( Graphics/Blank/Style.hs, /home/endgame/code/blank-canvas/dist-newstyle/build/x86_64-linux/ghc-8.6.5/blank-canvas-0.8/build/Graphics/Blank/Style.o )

Graphics/Blank/Style.hs:253:19: error:
    Not in scope: type constructor or class ‘MonadFail’
    |
253 | readColourName :: MonadFail m => String -> m (Colour Double)
```

**Comment by endgame** [comment]
I wonder if we have slightly different versions of packages, and one of your deps re-exports MonadFail in a module, but mine doesn't? I have attached the output of `ghc-pkg list`:

[pkgs.txt](https://github.com/ku-fpg/blank-canvas/files/4127974/pkgs.txt)

**Comment by RyanGlScott** [comment]
Thanks for posting the build plan you were using, as that helped me realize the real issue. Namely, `blank-canvas` succeeds when built against `base-compat-0.11` or later but not against older versions. Case in point:

```
$ cabal new-build -w /opt/ghc/8.6.5/bin/ghc --constraint="base-compat<0.11"
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - blank-canvas-0.8 (lib) (first run)
Preprocessing library for blank-canvas-0.8..
Building library for blank-canvas-0.8..
[12 of 18] Compiling Graphics.Blank.Style ( Graphics/Blank/Style.hs, /home/rgscott/Documents/Hacking/Haskell/travis-maintenance/checkout/ku-fpg/blank-canvas/dist-newstyle/build/x86_64-linux/ghc-8.6.5/blank-canvas-0.8/build/Graphics/Blank/Style.o ) [Prelude.Compat changed]

Graphics/Blank/Style.hs:253:19: error:
    Not in scope: type constructor or class ‘MonadFail’
    |
253 | readColourName :: MonadFail m => String -> m (Colour Double)
    |                   ^^^^^^^^^
```

This suggests that `blank-canvas`' lower version bounds on `base-compat` are inaccurate. In light of this, I think a prudent fix would be to adjust them to `base-compat >= 0.11 && ...` in the following places:

https://github.com/ku-fpg/blank-canvas/blob/c82b42d767283fd86023ce259fcdeea4d2c15724/blank-canvas.cabal#L77

https://github.com/ku-fpg/blank-canvas/blob/c82b42d767283fd86023ce259fcdeea4d2c15724/wiki-suite/wiki-suite.cabal#L19

https://github.com/ku-fpg/blank-canvas/blob/c82b42d767283fd86023ce259fcdeea4d2c15724/examples/blank-canvas-examples.cabal#L60

https://github.com/ku-fpg/blank-canvas/blob/c82b42d767283fd86023ce259fcdeea4d2c15724/examples/blank-canvas-examples.cabal#L74

https://github.com/ku-fpg/blank-canvas/blob/c82b42d767283fd86023ce259fcdeea4d2c15724/examples/blank-canvas-examples.cabal#L126

https://github.com/ku-fpg/blank-canvas/blob/c82b42d767283fd86023ce259fcdeea4d2c15724/examples/blank-canvas-examples.cabal#L211

Would you be willing to do this?

**Comment by endgame** [comment]
I can do this, but why not add the explicit import for `MonadFail` and keep things working with the wider range of `base-compat` dependencies? In particular, current stackage LTS (and therefore the default in nixpkgs) is still 0.10.5.

**Comment by RyanGlScott** [comment]
Either design would work, but I personally prefer the uniformity of just having `MonadFail` exported by `Prelude.Compat` on all versions of GHC (which is only possible with `base-compat >= 0.11`). It's simpler and requires fewer qualified imports.

I'm not too worried about Stackage here, since this bug is only present in the HEAD version of `blank-canvas` and not the current Hackage release. It's very likely that a Stackage release featuring `base-compat-0.11.*` will debut well before the next major Hackage release of `blank-canvas`.

**Comment by endgame** [comment]
I could have sworn I had this failure using only hackage packages, but I cannot reproduce it. Bound-tightening PR provided.
